spring:
  application:
    name: "app"
  datasource:
    url: jdbc:sqlite:app.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.community.dialect.SQLiteDialect